### PR TITLE
add support for enchanced connection

### PR DESCRIPTION
**Pull request by kele6ra**
Added capability of enhanced connection from extended features of ble5

### CODE REVIEW

**Comment by Apollon77** [comment]
@kele6ra DO you maybe have alink to the relevant specs?

**Review by rzr — COMMENTED** [review]
hi , it would be nice to have all cleanup/style changes in a separate commit

**Comment by kele6ra** [comment]
> hi , it would be nice to have all cleanup/style changes in a separate commit



> hi , it would be nice to have all cleanup/style changes in a separate commit

Hello, yes. I will remove style changes, sorry for it. I forget that setup styler for vsc before.

**Comment by Apollon77** [comment]
@kele6ra Fine to include the style changes ... just in a separate commit so that it can be reviewed easier

**Comment by kele6ra** [comment]
> @kele6ra Fine to include the style changes ... just in a separate commit so that it can be reviewed easier

add style changes for cpp and h files

**Review by rzr — APPROVED** [review]
Extra check welcome , note you could have more cleanup in 2d patch feel free to improve , or we can merge it that way

**Comment by kele6ra** [comment]
> Extra check welcome , note you could have more cleanup in 2d patch feel free to improve , or we can merge it that way

I have checked it during implementation (ubnutu 20) with some sensors with CodedPHY and my colleagues are checking it now

**Comment by Apollon77** [comment]
I plan to review against specs next days ... also to get a bit into that specs topic ... but if it works this is probably saying more. :-)

**Pull request merged**
