### PR TITLE
Make sure to only have one cleanup interval

### PR DESCRIPTION
**Pull request by Apollon77**

### CODE REVIEW

**Comment by Apollon77** [comment]
@rzr @splitice Please review

**Comment by rzr** [comment]
lgtm , i am wondering if the"if" is needed here too

**Comment by Apollon77** [comment]
formally on first call of start there is no timer set ... Yes clearInterval should silently ignore when called with an "invalid value" but I personally think thats bad code style :-)

**Comment by splitice** [comment]
Makes sense to me.

We moved away from Bluetooth hci socket for a fork of node raw socket btw. We already maintained a fork of that project for other components and it made sense for us.

Only compatible with Linux user channel mode (which in our experience is more reliable anyway)

**Comment by Apollon77** [comment]
@splitice What are the benefits of the node raw socket? If it is "better" then why not also integrating it into the noble fork from here as alternative or such?

**Pull request merged**
