### PR TITLE
Release 0.5.3-9

### PR DESCRIPTION
**Pull request by AlCalzone**

### CODE REVIEW

**Comment by Apollon77** [comment]
@rzr relates to https://github.com/abandonware/node-bluetooth-hci-socket/issues/38 to release it.

PR comes from a collegue because I can not even build package-lock because working on a mac :-)

Please approve

**Review by rzr — APPROVED** [review]

**Comment by Apollon77** [comment]
So, now we would ideally need the same for noble, right? :-) ... tp have a new version that forces to get the update to the users

**Comment by rzr** [comment]
humm not that easy we need to check what went wrong with:


https://github.com/abandonware/node-bluetooth-hci-socket/actions/runs/3711237998/jobs/6291451658#step:5:11

**Comment by Apollon77** [comment]
@rzr Thank you , but I think the nobile one was not correct, see https://github.com/abandonware/noble/commit/29166df77354275801b5018e9dd5553d258acef5#r93296429

**Comment by rzr** [comment]
yes I wanted to check the publish process feel free to bump it too
see:
https://github.com/abandonware/noble/commit/29166df77354275801b5018e9dd5553d258acef5#commitcomment-93394730

**Pull request merged**
