### PR TITLE
npm: Update dependencies to current

### PR DESCRIPTION
**Pull request by rzr**
Change-Id: Id56c95fbb8ff2ce650d0d8c1635f38a1fd59010e
Signed-off-by: Philippe Coval <rzr@users.sf.net>

### CODE REVIEW

**Comment by rzr** [comment]
Is @abandonware/reviewers able to merge this ?

**Comment by Apollon77** [comment]
Lgtm

**Comment by rzr** [comment]
thanks can I suggest to join abandonware maintainers team 

Please open a PR like this one:

https://github.com/abandonware/noble/pull/10

**Review by mrstegeman — APPROVED** [review]

**Comment by mrstegeman** [comment]
Why is there an AppVeyor build??

**Comment by rzr** [comment]
Because windows is supposed to be supported ?

Relate-to: https://github.com/abandonware/node-bluetooth-hci-socket/issues/10

I am not sure it ever worked , this can be ignored until #10 is fixed

Please @abandonware/maintainers  rebase and merge, if not granted let me know

**Pull request merged**
