### PR TITLE
Release 0.5.3-10

### PR DESCRIPTION
**Pull request by Apollon77**
* update deps in one commit
* increase version for release in second commit

### CODE REVIEW

**Comment by Apollon77** [comment]
@rzr ready to merge for release

**Comment by rzr** [comment]
thanks a lot , would you like to maintain this in longer term ?

**Comment by Apollon77** [comment]
I'm ok if you give me access to the orga, then I would love to support in maintaning it

**Comment by rzr** [comment]
Well i have created @adoptware too I need to betatest a flow but first how can @abandonware trust you ? :)
see procedure detailed at:
 https://abandonware.github.io/

**Comment by Apollon77** [comment]
@rzr Please check out my GitHub profile ... https://github.com/Apollon77, my contriibutions ad history shown there. This should be proof enough. If not, then also honestly, I have enough other projects to maintain where users and maintainers trust me

Bildschirm­foto 2023-01-03 um 18 07 33

**Comment by rzr** [comment]
impressive, please open pullrequest for maintainer file as suggested above and let's resume our talk there

**Pull request merged**
