### PR TITLE
Connect / Disconnect workaround

### PR DESCRIPTION
**Pull request by splitice**
This is a re-submission of PR #32

### CODE REVIEW

**Comment by rzr** [comment]
Please rebase and double check the appveyor or open an issue to track this bot which can be disabled in next change

**Comment by rzr** [comment]
is this easy to fix ? :

https://ci.appveyor.com/project/rzr/node-bluetooth-hci-socket/builds/41824764

**Comment by splitice** [comment]
@rzr yes, drop support for node 10 (it's out of support anyway).

FYI I'm working on a complete overhaul of this workaround to resolve memory leaks present in both this version and the original (they leak the l2cap sockets).

My first attempt wasnt successful as it breaks on certain BT implementations (e.g Broadcom) that output reconnections as:
1. Connect Device 1 (handle 1)
2. Connect Device 1 (handle 2)
3. Disconnect Device 1 (handle 1)

A re-engineering of the workaround is required to handle cases like this

**Comment by splitice** [comment]
#34

**Pull request closed without merging**
