### PR TITLE
Connect / Disconnect workaround

### PR DESCRIPTION
**Pull request by splitice**
Not ready to merge

Also includes a build command `npm run build` for QoL during development

### CODE REVIEW

**Comment by splitice** [comment]
Relates to #31

**Comment by splitice** [comment]
Up to this point the patch is minor and largely deals with handling edge cases (i.e socket errors)

**Comment by rzr** [comment]
Please rebase and update PR title if ready to be merged

**Comment by splitice** [comment]
Today this PR can be considered complete as far as Noble compatibility (I put it through it's paces)

I don't have any bleno knowledge, if someone wants to test it for bleno feel free to submit results

**Comment by rzr** [comment]
tests feedback welcome

**Comment by rzr** [comment]
please preserve other files and open other PR and explain why they should be removed

**Comment by rzr** [comment]
may your squash changes ?

**Comment by splitice** [comment]
rzr I didnt realize I didnt pr as as a feature branch (my bad). This next set of commits is experimental (tried to fix npm 7 and some issues with late version npm 6). I'll squash / remove before this is likely to merge.

**Comment by rzr** [comment]
it's not a problem, this way you can check CI results, a way to make it it clear it's a WIP is to set PR to draft to make sure it won't be merged until ready.

**Comment by rzr** [comment]
I think change set is good to be rebased , squashed and then merged ?

**Comment by splitice** [comment]
@rzr I'll fix this or do that it ends at  94e1a2607e54b454314d308e64818d79ab19c008 for you this week.

**Comment by splitice** [comment]
Superceeded by #33

**Pull request closed without merging**
