### PR TITLE
Node 12 compatibility

### PR DESCRIPTION
**Pull request by akx**
This PR adds compatibility for the Node 12.x series, as required for my downstream project Ruuvidriver: https://github.com/akx/ruuvidriver/pull/3

### CODE REVIEW

**Comment by rzr** [comment]
Thanks please also forward patch upstream and crosslink URL

**Comment by akx** [comment]
> Thanks please also forward patch upstream and crosslink URL

Do you mean backporting this patch onto upstream master, or just opening an issue attempting to notify upstream about these changes?

**Comment by rzr** [comment]
Opening the issue is a good start and should be enough, then It will be appreciated that you also comment the pending PRs, and eventually pick and port them  to @abandonware fork if relevent, then I will release a new version, does this sound like a good plan?

**Comment by akx** [comment]
Alright, I opened https://github.com/noble/node-bluetooth-hci-socket/issues/114 in the upstream repo. Re the other PRs in upstream, I can maybe take a look, sure. :)

**Comment by janhaa** [comment]
Can I help you with this somehow? Want to use latest node version, but this issue is preventing it.

**Comment by mrstegeman** [comment]
@rzr Can you do a new release?

**Comment by rzr** [comment]
I can try as soon  I get a better connectivity

**Comment by rzr** [comment]
https://www.npmjs.com/package/@abandonware/bluetooth-hci-socket/v/0.5.3-3 release

Btw please angine fix appvendor then i will use Travis to publish on pushed tag

**Pull request merged**
